module.exports = {
  "random": false,
  "authPass": null,
  "useOnlinePac": false,
  "TTL": 0,
  "global": false,
  "reconnectTimes": 3,
  "index": 0,
  "proxyType": 0,
  "proxyHost": null,
  "authUser": null,
  "proxyAuthPass": null,
  "isDefault": false,
  "pacUrl": null,
  "proxyPort": 0,
  "randomAlgorithm": 0,
  "proxyEnable": false,
  "enabled": true,
  "autoban": false,
  "proxyAuthUser": null,
  "shareOverLan": false,
  "localPort": 1080,
};
